---
title: '1: Create Samples & Variables'
author: "Maxwell Austensen"
date: '`r Sys.Date()`'
output:
  github_document: default
  html_notebook: default
subtitle: AEM Replication
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Install packages if needed
package_list <- c("haven", "stringr", "tidyverse", "janitor", "feather", "knitr", "rmarkdown")
new_packages <- package_list[!package_list %in% installed.packages()[,"Package"]]
if(length(new_packages)) install.packages(new_packages)

library(haven)
library(stringr)
library(tidyverse)
library(janitor)
library(feather)

# Set directories
raw_ <- "/Users/Maxwell/Box Sync/aem/replication/data/raw/"
clean_ <- "/Users/Maxwell/Box Sync/aem/replication/data/clean/"
```

```{r}
# load function to assign poverty threshold
source("get_pov_threshold_1990.R")
```

```{r}
raw <- read_stata(str_c(raw_, "usa_00005.dta"))
```

```{r}
names(raw) <- names(raw) %>% str_to_lower()
raw <- raw %>% zap_labels()
raw %>% select(noquote(order(colnames(raw)))) %>% glimpse()
```

```{r}
mothers <- 
  raw %>%
  group_by(serial) %>% 
  # Create variables that require info on all ousehold members (eg. standardized household income)
  mutate(hh_adults = sum(age >= 18, na.rm = TRUE),
         hh_children = sum(age < 18, na.rm = TRUE),
         hh_head_65p = if_else(pernum == 1, if_else(age >= 65, 1, 0), NA_real_) %>% sum(na.rm = TRUE),
         inc_adjuster = (hh_adults + (0.7 * hh_children)) ^ 0.7,
         hh_income = if_else(hhincome == 9999999, NA_real_, hhincome),
         hh_income_std = if_else(is.na(hh_income), NA_real_, hh_income / inc_adjuster)) %>% 
  ungroup() %>% 
  filter(between(bpl, 1, 120), # US born (inc'l us territories etc.)
         race == 1, # white
         sex == 2, # female
         between(age, 21, 40), # age 21-40
         between(marrno, 1, 2), # ever married
         between(agemarr, 17, 26), # married age 17-26
         between(chborn, 2, 13), # ever child
         between(marst, 1, 4), # ever married but not widow
         qage == 0, # not allocated: age
         qchborn == 0, # not allocated: chilren born
         qmarrno == 0, # not allocated: married
         qmarst == 0, # not allocated: marital status
         qagemarr== 0, # not allocated: married age
         qrelate == 0, # not allocated: relation to household head
         qsex == 0) # not allocated: sex
```

```{r}
children <-
  raw %>% 
  filter(momloc != 0,
         stepmom == 0) %>% 
  group_by(serial, momloc) %>% 
  mutate(children_mom  = n()) %>% # number of mother's children in household
  filter(age == max(age)) %>% # Keep only the oldest (can be multiple oldest if same age in years)
  mutate(max_age = max(age),
         same_qtr = sum(birthqtr == lag(birthqtr), na.rm = TRUE),
         twin = if_else(same_qtr > 0, 1, 0)) %>%
  arrange(serial, desc(age), birthqtr) %>% 
  filter(row_number() == 1) %>% # keep only one child if twin
  ungroup()

names(children) <- names(children) %>% str_c("_c")

# children %>% get_dupes(serial, momloc) # no dupes
```

```{r}
sample1 <-
  left_join(mothers, children, by = c("serial" = "serial_c", "pernum" = "momloc_c")) %>%
  filter(is.na(qage_c) | qage_c == 0, # not allocated: child's age
         is.na(qsex_c) | qsex_c == 0, # not allocated: child's sex
         is.na(qrelate_c) | qrelate_c == 0, # not allocated: child's relation to head of household
         is.na(qbirthmo_c) | qbirthmo_c == 0) %>% # not allocated: child's birth month
  filter(bpl <= 56,
         gq == 1,
         !is.na(hh_income)) %>% 
  mutate(marriage_ended = if_else(marst %in% c(3, 4) | marrno == 2, 1, 0),
         firstborn_girl = if_else(sex_c == 2, 1, 0),
         educ_yrs = if_else(higrade < 4, 0, higrade - 3),
         age_birth = age - age_c,
         age_married = agemarr,
         marital_status = if_else(marst %in% c(1, 2) & marrno == 2, 1, 0),
         urban = if_else(metarea == 0, 0, 1),
         n_children = if_else(chborn <= 1, 0, chborn - 1),
         children_mom = children_mom_c,
         hh_income_1990 = hh_income * 1.72,
         pov_threshold_1990 = pmap_dbl(list(hh_adults, hh_children, hh_head_65p), get_pov_treshold_1990),
         poverty_status = if_else(hh_income_1990 < pov_threshold_1990, 1, 0),
         woman_inc = if_else(inctot == 9999999, NA_real_, if_else(inctot == -009995, -9900, inctot)),
         nonwoman_inc = hh_income - woman_inc,
         woman_earn = if_else(incwage %in% c(999999, 999998), NA_real_, incwage),
         employed = if_else(empstat == 1, 1, 0),
         weeks_worked = wkswork1,
         hours_worked = uhrswork,
         state_birth = bpl,
         state_current = statefip) %>%
  select(serial,
         pernum,
         perwt,
         hh_adults,
         hh_children,
         hh_head_65p,
         state_birth,
         state_current,
         marriage_ended,
         firstborn_girl,
         educ_yrs,
         age_birth,
         age_married,
         marital_status,
         urban,
         n_children,
         nchild,
         children_mom,
         hh_income_std,
         hh_income,
         hh_income_1990,
         pov_threshold_1990,
         poverty_status,
         nonwoman_inc,
         woman_inc,
         woman_earn,
         employed,
         weeks_worked,
         hours_worked,
         age,
         age_c,
         twin_c)

# get_dupes(sample1, serial) # no dupes

# Paper results: 662,204
nrow(sample1)
```

```{r}
sample2 <- 
  sample1 %>% 
  filter(n_children == children_mom, 
         age_c < 18, 
         twin_c != 1)

# Paper results: 535,887
nrow(sample2)
```

```{r}
sample3 <-
  sample2 %>% 
  mutate(marr_len = age - age_married,
         marr_yr_born = marr_len - age_c) %>% 
  filter(between(marr_yr_born, 0, 5)) %>%
  select(-marr_len, - marr_yr_born)

# Paper results: 465,595
nrow(sample3)
```

```{r}
write_feather(sample1, str_c(clean_, "sample1.feather"))
write_feather(sample2, str_c(clean_, "sample2.feather"))
write_feather(sample3, str_c(clean_, "sample3.feather"))
```



