---
title: "Dartmouth_docsPCSA"
output:
  github_document: default
  html_notebook: default
date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(stringr); library(foreign); library(QuantPsyc); library(psych); library(knitr); library(tidyverse)
```

```{r}
# 2010 raw data
dart_raw <- read.dbf("../dropbox/capstone/2010 data/p_103113_1.dbf", as.is = TRUE)
names(dart_raw) <- names(dart_raw) %>% str_to_lower()

dart_raw2 <- read.dbf("../dropbox/capstone/2010 data/p_103113_2.dbf", as.is = T)
names(dart_raw2) <- names(dart_raw2) %>% str_to_lower()

dart_np <- read.dbf("../dropbox/capstone/2010 data/p_cnm_np_122013.dbf", as.is = T)
names(dart_np) <- names(dart_np) %>% str_to_lower()
```


```{r}
# limit to NYC PCSAs

dart_np$pcsa <-as.numeric(dart_np$pcsa)

xwalk <- read_csv("../Dropbox/capstone/zcta00_pcsa10_xwalk.csv") %>% distinct(pcsa, pcsa_name)
dart_np <- semi_join(dart_np, xwalk, by = "pcsa")

dart_np <-
  dart_np %>%
  transmute(pcsa = pcsa,
    pcsa_l = pcsa_l,
    cnm_fte = p_cnmfte, 
    np_fte = p_npfte
  ) %>%
  mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))
```

```{r}
dart_raw2$pcsa <- as.numeric(dart_raw2$pcsa)
dart_raw2 <- semi_join(dart_raw2, xwalk, by = "pcsa")

dart_fem <-
  dart_raw2 %>%
  transmute(pcsa = pcsa,
    pcsa_l = pcsa_l,
    fem15_44 = pp12i30 + pp12i31 + pp12i32 + pp12i33 + pp12i34 + pp12i36 + pp12i37 + pp12i38
  ) %>%
    mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))
```

```{r}
gentxwalk <- 
  read_csv("../dropbox/capstone/pcsa_gent_xwalk.csv", col_types = cols(pcsa = "c")) %>% 
  select(pcsa, gent_status) %>% 
  filter(!is.na(gent_status))

gentxwalk$pcsa <- as.numeric(gentxwalk$pcsa)
gentxwalk$gent_status <- ordered(gentxwalk$gent_status, levels = c("Non-Gentrifying", "Gentrifying", "High Income"))

```

```{r}
dart_raw$pcsa <- as.numeric(dart_raw$pcsa)
dart_raw <- semi_join(dart_raw, xwalk, by = "pcsa")

dart_nyc <- 
  dart_raw %>% 
  transmute(
    pcsa = pcsa,
    pcsa_l = pcsa_l,
    pcphys = pg_doc,
    famprac = pf_doc, 
    internist = pi_doc,
    specialist = ps_doc,
    obgyn = po_doc,
    nonfedpcp = pg_nfeddoc,
    nonfedspec = ps_nfeddoc,
    nonfedob = po_nfeddoc,
    img_pcp = pg_img,
    img_spec = ps_img,
    img_ob = po_img,
    pa_pcp = ppa_pc,
    pa_spec = ppa_pc_3sp, #GP/IM/Pediatrics PAs - as specialists
    pa_ob = ppa_pc_ob, #ob pa
    pa_oth = ppa_pc_oth, #geriatrics or unk specialty PA
    partb_pcp = pvt_pc10, #pc visits Part b only
    partb_amb = pvt_am10, #ambulatory visits part b only
    edvt = pvt_ed10, #est total number of ED visits per day
    pcpvt_rhc = pvt_rhc10,
    pcpvt_fqhc = pvt_fqhc10,
    medicare_acscd = pacs_10, #acs discharges
    medicare_denom = pbene_n10, #total bene pop for 2010, all medicare, not part-specific
    pcpdenom = pvden_10, # denom for PCP rate
    totpop = page00_14 + page15_64 + page65_up, 
    hospdenom = phden_10,
    ppop_pcp = ppop_gdoc,
    acs_crudert = pcracs_10, #their calculated CR for ACSDs
     ed_crudert = pcr_ed10, #their calculated CR for ed visits
    pcp_crudert = pcr_pc10 # their calculted CR for pcp visits
  ) %>% 
  mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .))) %>%
  inner_join(dart_np, by = "pcsa") %>%
  inner_join(dart_fem, by = "pcsa") %>%
  inner_join(gentxwalk, by = "pcsa")

dart_nyc$pcpvt_fqhc[is.na(dart_nyc$pcpvt_fqhc)] <- 0 
dart_nyc$pcpvt_rhc[is.na(dart_nyc$pcpvt_rhc)] <- 0 

dart_nyc$pcpvt <- dart_nyc$partb_pcp + dart_nyc$pcpvt_rhc + dart_nyc$pcpvt_fqhc  #total pcp visits for part B and OTP

```

```{r}
dart_nyc$physicians <- dart_nyc$pcphys + dart_nyc$specialist + dart_nyc$obgyn + dart_nyc$famprac + dart_nyc$internist
dart_nyc$pa <- dart_nyc$pa_ob + dart_nyc$pa_pcp + dart_nyc$pa_spec + dart_nyc$pa_oth
dart_nyc$obstets <- dart_nyc$obgyn + dart_nyc$pa_ob + dart_nyc$cnm_fte
dart_nyc$allpcp <- dart_nyc$pcphys + dart_nyc$np_fte + dart_nyc$pa_pcp #should we include dart_nyc$famprac & dart_nyc$internist ??
dart_nyc$specs <- dart_nyc$specialist + dart_nyc$pa_spec + dart_nyc$pa_oth
dart_nyc$allimg <- dart_nyc$img_ob + dart_nyc$img_pcp + dart_nyc$img_spec
```

```{r}
# add PCSA-level doc ratios
dart_nyc <- 
  mutate(dart_nyc, physician_rat = if_else(physicians !=0, (totpop/ physicians), NA_real_),
         pa_rat = if_else(pa !=0, (totpop/pa), NA_real_),
         np_rat = if_else(np_fte !=0, (totpop/ np_fte), NA_real_),
         cnm_rat = if_else(cnm_fte != 0, (fem15_44 /cnm_fte), NA_real_),
         allpcp_rat = if_else(allpcp !=0, (totpop / allpcp), NA_real_),
         specs_rat = if_else(specs != 0, (totpop / specs), NA_real_),
         obstets_rat = if_else(obstets !=0, (fem15_44 / obstets), NA_real_),
         img_rat = if_else(allimg != 0, (totpop / allimg), NA_real_))

# add PCSA-level visit rates
dart_nyc <- mutate(dart_nyc, acscd_rt = if_else(hospdenom != 0, (medicare_acscd / hospdenom)*1000, NA_real_),
                   pcpvt_rt = if_else(pcpdenom != 0, (pcpvt/ pcpdenom)*100, NA_real_),
                   edvt_rt = if_else(pcpdenom !=0, (edvt / pcpdenom)*1000, NA_real_))
```


```{r}

##confirm denominators
# test <- cbind.data.frame(dart_nyc$ed_crudert, dart_nyc$ed_rt, dart_nyc$pcp_crudert, dart_nyc$pcp_rt, dart_nyc$acs_crudert, dart_nyc$acscd_rt)
# 
# test$ed_pcdenom <- dart_nyc$edperday/dart_nyc$pcpdenom
# 
# test$acsdenom_calc <- dart_nyc$medicare_acscd/dart_nyc$acs_crudert ##matches hosp denom * 1000
# 
# dart_nyc$eddenom_calc <- dart_nyc$edperday/dart_nyc$ed_crudert
# dart_nyc$denom_diffs <- dart_nyc$pcpdenom - dart_nyc$eddenom_calc

```

```{r}
## bring in 99 data
raw99 <- read.csv("../dropbox/capstone/zcta99_pcsa2010.csv", as.is = TRUE)
names(raw99) <- names(raw99) %>% str_to_lower()

cms_pcsa <-read.csv("../dropbox/capstone/cms99_pcsa2010.csv", as.is = T)
names(cms_pcsa) <- names(cms_pcsa) %>% str_to_lower()
```

```{r}
cms_pcsa <-
  cms_pcsa %>%
  transmute(pcsa = pcsa2010, 
            pcpvt = zvt_pc99, #part B & outpatient file
            ambvt = zvt_am99, #part B & outpatient file
            edvt = zvt_ed99, #total #ED visits per bene per day by Med Part B bene resident in ZCTA
            pcpdenom = zvden_99, 
            eddenom = zhden_99, #hospitalization denom- not sure for ED
            totbene = zbene_n)

nyc99 <-
  raw99 %>%
  transmute(pcsa = pcsa2010,
            pcphys = zg_doc,
            specialist = zs_doc,
            obgyn = zo_doc,
            nonfedpcp = zg_nfeddoc,
            nonfedspec = zs_nfeddoc,
            nonfedob = zo_nfeddoc,
            img_pcp = zg_img,
            img_spec = zs_img,
            img_ob = zo_img,
            pa = zpa_tot, #total PAs
            pa_pcp = zpa_pc,
            pa_spec = zpa_spec,
            pa_ob = zpa_obgyn,
            pa_oth = zpa_oth,
            fqhcs = zfqhc,
            fem15_44 = zp012030 + zp012031 + zp012032 + zp012033 + zp012034 + zp012035 + zp012036 + zp012037 + zp012038,
            totpop = zage00_14 + zage15_64 + zage65_up) %>%
  inner_join(cms_pcsa, by = "pcsa") %>%
  inner_join(gentxwalk, by = "pcsa")

```

```{r}
nyc99$physicians <- nyc99$pcphys + nyc99$specialist + nyc99$obgyn
nyc99$obstets <- nyc99$obgyn + nyc99$pa_ob
nyc99$allpcp <- nyc99$pcphys + nyc99$pa_pcp
nyc99$specs <- nyc99$specialist + nyc99$pa_spec + nyc99$pa_oth
nyc99$allimg <- nyc99$img_ob + nyc99$img_pcp + nyc99$img_spec

```

```{r}
## 1999 data
# PCSA-level doc ratios
nyc99 <-
  mutate(nyc99, 
         physician_rat = if_else(physicians !=0, (totpop/ physicians), NA_real_),
         pa_rat = if_else(pa !=0, (totpop/pa), NA_real_),
         allpcp_rat = if_else(allpcp !=0, (totpop / allpcp), NA_real_),
         specs_rat = if_else(specs != 0, (totpop / specs), NA_real_),
         obstets_rat = if_else(obstets !=0, (fem15_44 / obstets), NA_real_),
         img_rat = if_else(allimg != 0, (totpop / allimg), NA_real_))

# PCSA-level visit rates
nyc99 <- 
  mutate(nyc99, pcpvt_rt = if_else(pcpdenom != 0, (pcpvt / pcpdenom)*100, NA_real_),
         edvt_rt = if_else(eddenom != 0, (edvt /eddenom)*1000, NA_real_))

```

```{r}
## COMBINE DATASETS

nyc99$year <- 1999
dart_nyc$year <- 2010

new99 <- 
  nyc99 %>%
  transmute(pcsa, year, gent_status, pcphys, specialist, obgyn, img_pcp, img_spec, img_ob, pa_pcp, pa_spec, pa_ob, pa_oth, fem15_44, totpop, pcpvt, edvt, physicians, pa, obstets, allpcp, specs, allimg, physician_rat, pa_rat, allpcp_rat, specs_rat, obstets_rat, img_rat, pcpvt_rt, edvt_rt, pcpdenom)

new99$cnm_fte <- NA
new99$np_fte <- NA
new99$cnm_rat <- NA
new99$np_rat <- NA
new99$medicare_acscd <- NA
new99$hospdenom <- NA
new99$acscd_rt <- NA
# new99 does not include internist and famprac, separately, but those are included in total physicians
# no np in pcp, no cnm in obstets for new99 

new99 <- 
  mutate(new99, 
         phys_p1000 = if_else(totpop !=0, (physicians/ totpop)*1000, NA_real_),
         pa_p1000 = if_else(totpop !=0, (pa/totpop)*1000, NA_real_),
         allpcp_p1000 = if_else(totpop !=0, (allpcp / totpop)*1000, NA_real_),
         specs_p1000 = if_else(totpop !=0, (specs/totpop)*1000, NA_real_),
         obstets_p1000 = if_else(totpop !=0, (obstets/totpop)*1000, NA_real_),
         img_p1000 = if_else(totpop !=0, (allimg/totpop)*1000, NA_real_))

new99$np_p1000 <- NA

new10 <-
  dart_nyc %>%
  transmute(pcsa, year, gent_status, pcphys, specialist, obgyn, img_pcp, img_spec, img_ob, pa_pcp, pa_spec, pa_ob, pa_oth, fem15_44, totpop, pcpvt, edvt, physicians, pa, obstets, allpcp, specs, allimg, physician_rat, pa_rat, allpcp_rat, specs_rat, obstets_rat, img_rat, pcpvt_rt, edvt_rt, pcpdenom, cnm_fte, np_fte, cnm_rat, np_rat, medicare_acscd, hospdenom, acscd_rt)

new10 <- 
  mutate(new10, 
         phys_p1000 = if_else(totpop !=0, (physicians/ totpop)*1000, NA_real_),
         pa_p1000 = if_else(totpop !=0, (pa/totpop)*1000, NA_real_),
         allpcp_p1000 = if_else(totpop !=0, (allpcp / totpop)*1000, NA_real_),
         specs_p1000 = if_else(totpop !=0, (specs/totpop)*1000, NA_real_),
         obstets_p1000 = if_else(totpop !=0, (obstets/totpop)*1000, NA_real_),
         img_p1000 = if_else(totpop !=0, (allimg/totpop)*1000, NA_real_),
         np_p1000 = if_else(totpop !=0, (np_fte/totpop)*1000, NA_real_))

fulldf <- bind_rows(new99, new10)
write.csv(fulldf, file = "../dropbox/capstone/fulldf.csv")

```

```{r}
rm(dart_raw, dart_raw2, raw99, dart_fem, dart_np, cms_pcsa) 

```

```{r}
#for maps
write.csv(new99, "../dropbox/capstone/map99.csv")

write.csv(new10, "../dropbox/capstone/map10.csv")

```

```{r}
# VISIT TABLES
vsttable <-
  fulldf %>%
  group_by(gent_status, year) %>%
  summarise(pcpvt_rt = sum(pcpvt[!is.na(pcpvt_rt)], na.rm = T) / sum(pcpdenom[!is.na(pcpvt_rt)], na.rm=T) * 100,
            edvt_rt = sum(edvt[!is.na(edvt_rt)], na.rm= T) / sum(pcpdenom[!is.na(edvt_rt)], na.rm=T) * 1000) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))

order_vec <- c("gent_status", "year", "pcpvt_rt", "edvt_rt")
kable(vsttable)

vstacs <- new10 %>%
  group_by(gent_status) %>%
  summarise(acscd_rt = sum(medicare_acscd[!is.na(acscd_rt)], na.rm=T) / sum(hospdenom[!is.na(acscd_rt)], na.rm=T) * 1000) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))
kable(vstacs)

# vsttable %>%
#   gather("var", "value", -gent_status) %>%
#   spread(gent_status, value) %>%
#   mutate(var = ordered(var, levels = order_vec)) %>%
#   arrange(var) %>%
#   kable()
```

```{r}
# DOC TABLES

doctable_ratios <-
  fulldf %>%
  group_by(gent_status, year) %>%
  summarise(physicians = sum(totpop)/ sum(physicians),
            pa = sum(totpop)/ sum(pa),
            allpcp = sum(totpop) / sum(allpcp),
            specs = sum(totpop) / sum(specs),
            obstets = sum(fem15_44) / sum(obstets),
            img = sum(totpop) / sum(allimg)) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))
  kable(doctable_ratios)

npcnm <- new10 %>%
  group_by(gent_status) %>%
  summarise(np = sum(totpop)/ sum(np_fte),
            cnm = sum(fem15_44) /sum(cnm_fte)) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))
  kable(npcnm)
```

