---
title: "Dartmouth_docsPCSA"
output:
  github_document: default
  html_notebook: default
date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(stringr); library(foreign); library(QuantPsyc); library(psych); library(knitr); library(tidyverse)
```

```{r}
# 2010 raw data
dart_raw <- read.dbf("../dropbox/capstone/2010 data/p_103113_1.dbf", as.is = TRUE)
names(dart_raw) <- names(dart_raw) %>% str_to_lower()

dart_raw2 <- read.dbf("../dropbox/capstone/2010 data/p_103113_2.dbf", as.is = T)
names(dart_raw2) <- names(dart_raw2) %>% str_to_lower()

dart_np <- read.dbf("../dropbox/capstone/2010 data/p_cnm_np_122013.dbf", as.is = T)
names(dart_np) <- names(dart_np) %>% str_to_lower()
```


```{r}
# limit to NYC PCSAs

dart_np$pcsa <-as.numeric(dart_np$pcsa)

xwalk <- read_csv("../Dropbox/capstone/tract_pcsa_xwalk.csv") %>% distinct(pcsa, pcsa_name)
dart_np <- semi_join(dart_np, xwalk, by = "pcsa")

dart_np <-
  dart_np %>%
  transmute(pcsa = pcsa,
    pcsa_l = pcsa_l,
    cnm_fte = p_cnmfte, 
    np_fte = p_npfte
  ) %>%
  mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))
```

```{r}
dart_raw2$pcsa <- as.numeric(dart_raw2$pcsa)
dart_raw2 <- semi_join(dart_raw2, xwalk, by = "pcsa")

dart_fem <-
  dart_raw2 %>%
  transmute(pcsa = pcsa,
    pcsa_l = pcsa_l,
    fem15_44 = pp12i30 + pp12i31 + pp12i32 + pp12i33 + pp12i34 + pp12i36 + pp12i37 + pp12i38
  ) %>%
    mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .)))
```

```{r}
gentxwalk <- 
  read_csv("../dropbox/capstone/pcsa_gent.csv", col_types = cols(pcsa = "c")) %>% 
  select(pcsa, gent_status) %>% 
  filter(!is.na(gent_status))

gentxwalk$pcsa <- as.numeric(gentxwalk$pcsa)
gentxwalk$gent_status <- ordered(gentxwalk$gent_status, levels = c("Non-Gentrifying", "Gentrifying", "High Income"))

```

```{r}
dart_raw$pcsa <- as.numeric(dart_raw$pcsa)
dart_raw <- semi_join(dart_raw, xwalk, by = "pcsa")

dart_nyc <- 
  dart_raw %>% 
  transmute(
    pcsa = pcsa,
    pcsa_l = pcsa_l,
    pcp = pg_doc,
    famprac = pf_doc, 
    internist = pi_doc,
    specialist = ps_doc,
    obgyn = po_doc,
    nonfedpcp = pg_nfeddoc,
    nonfedspec = ps_nfeddoc,
    nonfedob = po_nfeddoc,
    img_pcp = pg_img,
    img_spec = ps_img,
    img_ob = po_img,
    pa_pcp = ppa_pc,
    pa_spec = ppa_pc_3sp, #GP/IM/Pediatrics PAs - as specialists
    pa_ob = ppa_pc_ob, #ob pa
    pa_oth = ppa_pc_oth, #geriatrics or unk specialty PA
    partb_pcp = pvt_pc10, #pc visits Part b only
    partb_amb = pvt_am10, #ambulatory visits part b only
    edperday = pvt_ed10, #est total number of ED visits per day
    pcpvt_rhc = pvt_rhc10,
    pcpvt_fqhc = pvt_fqhc10,
    medicare_acscd = pacs_10, #acs discharges
    medicare_denom = pbene_n10, #total bene pop for 2010, all medicare, not part-specific
    pcpdenom = pvden_10, # denom for PCP rate
    totpop = page00_14 + page15_64 + page65_up, 
    hospdenom = phden_10,
    ppop_pcp = ppop_gdoc,
    acs_crudert = pcracs_10, #their calculated CR for ACSDs
     ed_crudert = pcr_ed10, #their calculated CR for ed visits
    pcp_crudert = pcr_pc10 # their calculted CR for pcp visits
  ) %>% 
  mutate_if(is.double, funs(if_else(. %in% c(-99, -999), NA_real_, .))) %>%
  inner_join(dart_np, by = "pcsa") %>%
  inner_join(dart_fem, by = "pcsa") %>%
  inner_join(gentxwalk, by = "pcsa")

dart_nyc$pcpvt_fqhc[is.na(dart_nyc$pcpvt_fqhc)] <- 0 
dart_nyc$pcpvt_rhc[is.na(dart_nyc$pcpvt_rhc)] <- 0 

dart_nyc$pcpvt_tot <- dart_nyc$partb_pcp + dart_nyc$pcpvt_rhc + dart_nyc$pcpvt_fqhc  #total pcp visits for part B and OTP

```

```{r}
dart_nyc$physicians <- dart_nyc$pcp + dart_nyc$specialist + dart_nyc$obgyn + dart_nyc$famprac + dart_nyc$internist
dart_nyc$pa <- dart_nyc$pa_ob + dart_nyc$pa_pcp + dart_nyc$pa_spec + dart_nyc$pa_oth
dart_nyc$obstets <- dart_nyc$obgyn + dart_nyc$pa_ob + dart_nyc$cnm_fte
dart_nyc$allpcp <- dart_nyc$pcp + dart_nyc$np_fte + dart_nyc$pa_pcp #should we include dart_nyc$famprac & dart_nyc$internist ??
dart_nyc$specs <- dart_nyc$specialist + dart_nyc$pa_spec + dart_nyc$pa_oth
dart_nyc$allimg <- dart_nyc$img_ob + dart_nyc$img_pcp + dart_nyc$img_spec
```

```{r} 
# functions for CIs
# Upper Limit = (1000 / n) (d + (1.96 x square root of d)) #
ci <- function(x , n , d) {
  l <- (x / sum(n))*((sum(d)) - (1.96 * sqrt(sum(d))))
  r <- (x / sum(n))*((sum(d)) + (1.96 * sqrt(sum(d))))
  output <-  paste0(signif(l, digits = 3), " , ", signif(r, digits = 3))
  return(output)
}

ci00 <- function(x, n, d, r) {
  l <- l <- (x / sum(n[!is.na(r)], na.rm = T))*((sum(d[!is.na(r)], na.rm = T)) - (1.96 * sqrt(sum(d[!is.na(r)], na.rm = T))))
  r <- (x / sum(n[!is.na(r)], na.rm = T))*((sum(d[!is.na(r)], na.rm = T)) + (1.96 * sqrt(sum(d[!is.na(r)], na.rm = T))))
  output <-  paste0(signif(l, digits = 3), ",", signif(r, digits = 3))
  return(output)
}
cimedicare <- function(x) {
  l <- (x / sum(dart_nyc$medicare_denom[!is.na(dart_nyc$acscd_rt)], na.rm=T))*((sum(dart_nyc$medicare_acscd[!is.na(dart_nyc$acscd_rt)], na.rm=T)) - (1.96 * sqrt(sum(dart_nyc$medicare_acscd[!is.na(dart_nyc$acscd_rt)], na.rm=T))))
  r <- (x / sum(dart_nyc$medicare_denom[!is.na(dart_nyc$acscd_rt)], na.rm=T))*((sum(dart_nyc$medicare_acscd[!is.na(dart_nyc$acscd_rt)], na.rm=T)) + (1.96 * sqrt(sum(dart_nyc$medicare_acscd[!is.na(dart_nyc$acscd_rt)], na.rm=T))))
  output <-  paste0(signif(l, digits = 4), ",", signif(r, digits = 4))
  return(output)
}

ci(1000, dart_nyc$totpop, dart_nyc$physicians)

```

```{r}
# add PCSA-level doc ratios
dart_nyc <- 
  mutate(dart_nyc, pa_rat = if_else(physicians !=0, (totpop/ physicians), NA_real_),
         np_rat = if_else(np_fte !=0, (totpop/ np_fte), NA_real_),
         cnm_rat = if_else(cnm_fte != 0, (fem15_44 /cnm_fte), NA_real_),
         allpcp_rat = if_else(allpcp !=0, (totpop / allpcp), NA_real_),
         specs_rat = if_else(specs != 0, (totpop / specs), NA_real_),
         obstets_rat = if_else(obstets !=0, (fem15_44 / obstets), NA_real_),
         img_rat = if_else(allimg != 0, (totpop / allimg), NA_real_))

# add PCSA-level visit rates
dart_nyc <- mutate(dart_nyc, acscd_rt = if_else(hospdenom != 0, (medicare_acscd / hospdenom), NA_real_),
                   pcp_rt = if_else(pcpdenom != 0, (pcpvt_tot / pcpdenom), NA_real_),
                   ed_rt = if_else(pcpdenom !=0, (edperday / pcpdenom), NA_real_))
```

```{r}

# sumtable <-
#   dart_nyc %>%
#   group_by(gent_status) %>%
#   summarise(physicians_rt = sum(physicians) / sum(totpop)*1000,
#             phys_ci = ci(1000, totpop, physicians),
#             pa_rt = sum(pa) / sum(totpop)*10000,
#             pa_ci = ci(10000, totpop, pa),
#             np_rt = sum(np_fte) / sum(totpop)*100000,
#             np_ci = ci(100000, totpop, np_fte),
#             cnm_rt = sum(cnm_fte) / sum(fem15_44)*10000,
#             cnm_ci = ci(10000, fem15_44, cnm_fte),
#             allpcp_rt = sum(allpcp) / sum(totpop)*1000,
#             allpcp_ci = ci(1000, totpop, allpcp),
#             specs_rt = sum(specs) / sum(totpop)*1000,
#             specs_ci = ci(1000, totpop, specs),
#             obstets_rt = sum(obstets) / sum(fem15_44)*10000,
#             obstets_ci = ci(10000, fem15_44, obstets),
#             img_rt = sum(allimg) / sum(totpop)*1000,
#             img_ci = ci(1000, totpop, allimg)) %>%
#     mutate_if(is.numeric, funs(round(., digits = 2)))

# kable(sumtable)

# order_vec <- c("gent", "physicians_rt", "phys_ci", "pa_rt", "pa_ci", "np_rt", 
# "np_ci", "cnm_rt", "cnm_ci", "allpcp_rt", "allpcp_ci", "specs_rt", 
# "specs_ci", "obstets_rt", "obstets_ci", "img_rt", "img_ci", "acscd_rt") 
# 
# sumtable %>% 
#   gather("var", "value", -gent_status) %>% 
#   spread(gent_status, value) %>% 
#   mutate(var = ordered(var, levels = order_vec)) %>% 
#   arrange(var) %>% 
#   kable()


doctable_ratios <- 
  dart_nyc %>%
  group_by(gent_status) %>%
  summarise(physicians = sum(totpop)/ sum(physicians),
            pa = sum(totpop)/ sum(pa),
            np = sum(totpop)/ sum(np_fte), 
            cnm = sum(fem15_44) /sum(cnm_fte),
            allpcp = sum(totpop) / sum(allpcp), 
            specs = sum(totpop) / sum(specs),
            obstets = sum(fem15_44) / sum(obstets),
            img = sum(totpop) / sum(allimg)) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))
  kable(doctable_ratios)

order_vec <- c("gent_status", "physicians", "pa", "np", "cnm", "allpcp", "specs", "obstets", "img")

doctable_ratios %>%
  gather("var", "value", -gent_status) %>%
  spread(gent_status, value) %>%
  mutate(var = ordered(var, levels= order_vec)) %>%
  arrange(var) %>%
  kable()

```

```{r}

##confirm denominators
# test <- cbind.data.frame(dart_nyc$ed_crudert, dart_nyc$ed_rt, dart_nyc$pcp_crudert, dart_nyc$pcp_rt, dart_nyc$acs_crudert, dart_nyc$acscd_rt)
# 
# test$ed_pcdenom <- dart_nyc$edperday/dart_nyc$pcpdenom
# 
# test$acsdenom_calc <- dart_nyc$medicare_acscd/dart_nyc$acs_crudert ##matches hosp denom * 1000
# 
# dart_nyc$eddenom_calc <- dart_nyc$edperday/dart_nyc$ed_crudert
# dart_nyc$denom_diffs <- dart_nyc$pcpdenom - dart_nyc$eddenom_calc

## visit rate table
vsttable <- 
  dart_nyc %>%
  group_by(gent_status) %>%
  summarise(acscd_rt = sum(medicare_acscd[!is.na(acscd_rt)], na.rm=T) / sum(hospdenom[!is.na(acscd_rt)], na.rm=T) * 1000,
            pcp_rt = sum(pcpvt_tot[!is.na(pcp_rt)], na.rm = T) / sum(pcpdenom[!is.na(pcp_rt)], na.rm=T) * 100, 
            ed_rt = sum(edperday[!is.na(ed_rt)], na.rm= T) / sum(pcpdenom[!is.na(ed_rt)], na.rm=T) * 1000) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))

#2010 data
order_vec <- c("gent_status", "acscd_rt", "pcp_rt", "ed_rt")

options(scipen=999)

vsttable %>% 
  gather("var", "value", -gent_status) %>% 
  spread(gent_status, value) %>% 
  mutate(var = ordered(var, levels = order_vec)) %>% 
  arrange(var) %>% 
  kable()
```

```{r}
## bring in 99 data
raw99 <- read.csv("../dropbox/capstone/zcta99_pcsa2010.csv", as.is = TRUE)
names(raw99) <- names(raw99) %>% str_to_lower()

cms_pcsa <-read.csv("../dropbox/capstone/cms99_pcsa2010.csv", as.is = T)
names(cms_pcsa) <- names(cms_pcsa) %>% str_to_lower()
```

```{r}
cms_pcsa <-
  cms_pcsa %>%
  transmute(pcsa = pcsa2010, 
            pcpvt = zvt_pc99, #part B & outpatient file
            ambvt = zvt_am99, #part B & outpatient file
            edvt = zvt_ed99, #total #ED visits per bene per day by Med Part B bene resident in ZCTA
            pcpdenom = zvden_99, 
            eddenom = zhden_99, #hospitalization denom- not sure for ED
            totbene = zbene_n)

nyc99 <-
  raw99 %>%
  transmute(pcsa = pcsa2010,
            pcp = zg_doc,
            specialist = zs_doc,
            obgyn = zo_doc,
            nonfedpcp = zg_nfeddoc,
            nonfedspec = zs_nfeddoc,
            nonfedob = zo_nfeddoc,
            img_pcp = zg_img,
            img_spec = zs_img,
            img_ob = zo_img,
            pa_tot = zpa_tot,
            pa_pcp = zpa_pc,
            pa_spec = zpa_spec,
            pa_ob = zpa_obgyn,
            pa_oth = zpa_oth,
            fqhcs = zfqhc,
            fem15_44 = zp012030 + zp012031 + zp012032 + zp012033 + zp012034 + zp012035 + zp012036 + zp012037 + zp012038,
            totpop = zage00_14 + zage15_64 + zage65_up) %>%
  inner_join(cms_pcsa, by = "pcsa") %>%
  inner_join(gentxwalk, by = "pcsa")

```

```{r}
nyc99$physicians <- nyc99$pcp + nyc99$specialist + nyc99$obgyn
nyc99$obstets <- nyc99$obgyn + nyc99$pa_ob
nyc99$allpcp <- nyc99$pcp + nyc99$pa_pcp
nyc99$specs <- nyc99$specialist + nyc99$pa_spec + nyc99$pa_oth
nyc99$allimg <- nyc99$img_ob + nyc99$img_pcp + nyc99$img_spec
```

```{r}
#1999 data
#sumtable99 <- 
#  nyc99 %>%
#  group_by(gent_status) %>%
#  summarise(physicians_rt = sum(physicians) / sum(totpop)*1000,
#            phys_ci = ci(1000, totpop, physicians),
#            pa_rt = sum(pa_tot) / sum(totpop)*10000,
#            pa_ci = ci(10000, totpop, pa_tot),
##            allpcp_rt = sum(allpcp) / sum(totpop)*1000,
#            allpcp_ci = ci(1000, totpop, allpcp), 
#            specs_rt = sum(specs) / sum(totpop)*1000,
#            specs_ci = ci(1000, totpop, specs),
#            obstets_rt = sum(obstets) / sum(fem15_44)*10000,
#            obstets_ci = ci(10000, fem15_44, obstets),
#            img_rt = sum(allimg) / sum(totpop)*1000,
#            img_ci = ci(1000, totpop, allimg)) %>%
#    mutate_if(is.numeric, funs(round(., digits = 2)))

table99_ratios <- 
  nyc99 %>%
  group_by(gent_status) %>%
  summarise(physicians = sum(totpop)/sum(physicians), 
            pa = sum(totpop)/ sum(pa_tot),
            allpcp = sum(totpop) / sum(allpcp),
            specialists = sum(totpop)/sum(specs),
            obstets = sum(fem15_44)/sum(obstets),
            img = sum(totpop)/sum(allimg)) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))

#kable(sumtable99)
#order_vec <- c("gent_status", "physicians_rt", "phys_ci", "pa_rt", "pa_ci", "allpcp_rt", "allpcp_ci", "specs_rt", #"specs_ci", "obstets_rt", "obstets_ci", "img_rt", "img_ci") 

kable(table99_ratios)
order_vec <- c("gent_status", "physicians", "pa", "allpcp", "specialists", "obstets", "img") 


#sumtable99 %>% 
table99_ratios %>% 
 gather("var", "value", -gent_status) %>% 
  spread(gent_status, value) %>% 
  mutate(var = ordered(var, levels = order_vec)) %>% 
  arrange(var) %>% 
  kable()

```

```{r}
# 1999 data
nyc99 <- mutate(nyc99, pcp_rt = if_else(pcpdenom != 0, (pcpvt / pcpdenom), NA_real_))
nyc99 <- mutate(nyc99, ed_rt = if_else(eddenom != 0, (edvt /eddenom), NA_real_))

#sum(nyc99$edvt) /sum(nyc99$eddenom)
#sum(nyc99$pcpvt) /sum(nyc99$pcpdenom)


vsttable99 <- 
  nyc99 %>%
  group_by(gent_status) %>%
  summarise(pcp_rt = sum(pcpvt[!is.na(pcp_rt)], na.rm = T) / sum(pcpdenom[!is.na(pcp_rt)], na.rm=T) * 100,
ed_rt = sum(edvt[!is.na(ed_rt)], na.rm= T) / sum(pcpdenom[!is.na(ed_rt)], na.rm=T) *1000) %>%
  mutate_if(is.numeric, funs(round(., digits = 2)))


order_vec <- c("gent_status", "pcp_rt", "ed_rt")

vsttable99 %>% 
  gather("var", "value", -gent_status) %>% 
  spread(gent_status, value) %>% 
  mutate(var = ordered(var, levels = order_vec)) %>% 
  arrange(var) %>% 
  kable()          
```

```{r}
#look at docs by age

dart_nyc <- cbind.data.frame(dart_nyc, dart_raw$pg_gt50doc, dart_raw$ps_gt50doc, dart_raw$po_gt50doc)
```

